input {
  file {
    path => "/usr/share/logstash/config/nginx/access.log"
    start_position => "beginning"
  }
}
filter {
  grok {
    match => { "message" => "%{IP:clientip} %{WORD:status_type} %{NUMBER:http_status}" }
  }
  mutate {
    remove_field => [ "host" ]
  }
}
output {
  stdout {
  }
 
  elasticsearch {
    hosts => [ "${ES_HOST}" ]
    data_stream => "true"

  }
}
